Repository GTNewHorizons/BloodMagic, pull requests merged in 2025-05, with the labels that each got.

#79 Polishes Alchemic Calcinator & Belljars
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockAlchemicCalcinator.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockBelljar.java
Labels: :construction: Testing on Zeta

#77 NEI Meteor Handler Revamp
  dependencies.gradle
  src/main/java/WayofTime/alchemicalWizardry/client/nei/IMCForNEI.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIAlchemyRecipeHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIAltarRecipeHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIBindingRitualHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIBloodOrbShapedHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIBloodOrbShapelessHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIConfig.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIMeteorRecipeHandler.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/widgets/BMNEIWidget.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/widgets/CostInfo.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/widgets/RadiusInfo.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/widgets/ReagentInfo.java
  src/main/java/WayofTime/alchemicalWizardry/client/nei/widgets/RitualInfo.java
  src/main/java/WayofTime/alchemicalWizardry/common/summoning/meteor/Meteor.java
  src/main/resources/assets/alchemicalwizardry/gui/nei/meteor.png
  src/main/resources/assets/alchemicalwizardry/lang/en_US.lang
Labels: enhancement, :construction: Testing on Zeta

#85 Orchestra of the Phantom Hands Improvements
  src/main/java/WayofTime/alchemicalWizardry/api/RoutingFocusLogic.java
  src/main/java/WayofTime/alchemicalWizardry/api/RoutingFocusParadigm.java
  src/main/java/WayofTime/alchemicalWizardry/common/items/routing/OutputRoutingFocus.java
  src/main/java/WayofTime/alchemicalWizardry/common/items/routing/RoutingFocus.java
  src/main/java/WayofTime/alchemicalWizardry/common/rituals/RitualEffectItemRouting.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicIgnMeta.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicLimitDefault.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicLimitGlobal.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicLimitIgnMeta.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicLimitMatchNBT.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicLimitModItems.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicMatchNBT.java
  src/main/java/WayofTime/alchemicalWizardry/common/routing/RoutingFocusLogicModItems.java
  src/main/resources/assets/alchemicalwizardry/lang/en_US.lang
  src/main/resources/assets/alchemicalwizardry/lang/ru_RU.lang
  src/main/resources/assets/alchemicalwizardry/lang/zh_CN.lang
  src/main/resources/assets/alchemicalwizardry/lang/zh_TW.lang
Labels: enhancement

#89 Allow the Orb of Armok to work from within a Blood Altar.
  dependencies.gradle
  src/main/java/WayofTime/alchemicalWizardry/api/items/interfaces/IBloodOrb.java
  src/main/java/WayofTime/alchemicalWizardry/common/tileEntity/TEAltar.java
Labels: enhancement

#91 Registry Ordering
  src/main/java/WayofTime/alchemicalWizardry/ModBlocks.java
  src/main/java/WayofTime/alchemicalWizardry/ModItems.java
Labels: refactor

#92 Texture Improvements
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockAltar.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockConduit.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockCrucible.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockCrystal.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockEnchantmentGlyph.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockHomHeart.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockPedestal.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockPlinth.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockSchematicSaver.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockSocket.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockStabilityGlyph.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockTeleposer.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BlockWritingTable.java
  src/main/java/WayofTime/alchemicalWizardry/common/block/BloodRune.java
  src/main/java/WayofTime/alchemicalWizardry/common/items/EnergyBlast.java
  src/main/java/WayofTime/alchemicalWizardry/common/items/energy/ItemAttunedCrystal.java
  src/main/java/WayofTime/alchemicalWizardry/common/items/energy/ItemTankSegmenter.java
  src/main/resources/assets/alchemicalwizardry/textures/blocks/SchematicSaver.png
  src/main/resources/assets/alchemicalwizardry/textures/items/BoundPickaxe_activated.png
Labels: enhancement, :construction: Testing on Zeta, refactor
