Repository GTNewHorizons/BloodMagic, pull requests merged in 2025-06, with the labels that each got.

#95 Show capacity of Blood Orbs in the tooltip.
  src/main/java/WayofTime/alchemicalWizardry/common/items/EnergyBattery.java
  src/main/resources/assets/alchemicalwizardry/lang/en_US.lang
  src/main/resources/assets/alchemicalwizardry/lang/zh_CN.lang
Labels: enhancement, safe for stable

#93 Show Required Reagents for Fillers Replaced by Reagents
  src/main/java/WayofTime/alchemicalWizardry/client/nei/NEIMeteorRecipeHandler.java
Labels: enhancement, :construction: Testing on Zeta, safe for stable

#98 Fix "Vis discount" Tooltip for Sanguine Armor
  src/main/java/WayofTime/alchemicalWizardry/common/items/thaumcraft/ItemSanguineArmour.java
  src/main/resources/assets/alchemicalwizardry/lang/en_US.lang
  src/main/resources/assets/alchemicalwizardry/lang/ru_RU.lang
  src/main/resources/assets/alchemicalwizardry/lang/zh_CN.lang
  src/main/resources/assets/alchemicalwizardry/lang/zh_TW.lang
Labels: bug, safe for stable
